-- create_staging.sql
-- Tujuan : Membuat schema staging dan tabel replika ODS
-- Target : dw_bankcredit (PostgreSQL)
 
DROP SCHEMA IF EXISTS stg CASCADE;
CREATE SCHEMA stg;
 
-- Tabel staging: stg.ods_loan_transactions
CREATE TABLE stg.ods_loan_transactions (
    application_id        INTEGER PRIMARY KEY,
    application_date      DATE,
    requested_amount      NUMERIC(18,2),
    tenor_months          INTEGER,
    purpose               VARCHAR(100),
    app_status            VARCHAR(30),
    customer_id           INTEGER,
    national_id           VARCHAR(30),
    customer_name         VARCHAR(100),
    date_of_birth         DATE,
    occupation            VARCHAR(50),
    monthly_income        NUMERIC(18,2),
    risk_segment          INTEGER,
    email                 VARCHAR(100),
    phone                 VARCHAR(20),
    credit_score          INTEGER,
    credit_grade          VARCHAR(10),
    rating_date           DATE,
    bureau_source         VARCHAR(30),
    product_id            INTEGER,
    product_code          VARCHAR(20),
    product_name          VARCHAR(100),
    product_type          VARCHAR(50),
    product_interest_rate NUMERIC(6,2),
    min_amount            NUMERIC(18,2),
    max_amount            NUMERIC(18,2),
    max_tenor_months      INTEGER,
    branch_id             INTEGER,
    branch_code           VARCHAR(20),
    branch_name           VARCHAR(100),
    city                  VARCHAR(50),
    region                VARCHAR(30),
    branch_opened_date    DATE,
    assessment_id         INTEGER,
    dti_ratio             NUMERIC(8,2),
    pd_score              NUMERIC(8,4),
    recommendation        VARCHAR(30),
    assessor_notes        VARCHAR(255),
    assessed_on           DATE,
    pledge_id             INTEGER,
    collateral_type_id    INTEGER,
    collateral_type_name  VARCHAR(100),
    ltv_ratio             NUMERIC(8,2),
    appraised_value       NUMERIC(18,2),
    document_ref          VARCHAR(50),
    pledge_date           DATE,
    approval_id           INTEGER,
    approver_id           INTEGER,
    approver_name         VARCHAR(100),
    approver_role         VARCHAR(50),
    approved_amount       NUMERIC(18,2),
    final_rate            NUMERIC(6,2),
    approval_date         DATE,
    decision              VARCHAR(20),
    disbursement_id       INTEGER,
    disbursed_amount      NUMERIC(18,2),
    disbursed_on          DATE,
    account_no            VARCHAR(30),
    channel               VARCHAR(30)
);
 
-- Tabel staging: stg.ods_loan_payments
CREATE TABLE stg.ods_loan_payments (
    payment_id       INTEGER PRIMARY KEY,
    disbursement_id  INTEGER,
    installment_no   INTEGER,
    principal        NUMERIC(18,2),
    interest         NUMERIC(18,2),
    due_date         DATE,
    paid_date        DATE,
    payment_status   VARCHAR(20),
    approval_id      INTEGER,
    disbursed_amount NUMERIC(18,2),
    disbursed_on     DATE,
    account_no       VARCHAR(30),
    channel          VARCHAR(30),
    application_id   INTEGER,
    approved_amount  NUMERIC(18,2),
    final_rate       NUMERIC(6,2),
    decision         VARCHAR(20),
    customer_id      INTEGER,
    customer_name    VARCHAR(100),
    product_id       INTEGER,
    product_code     VARCHAR(20),
    branch_id        INTEGER,
    branch_code      VARCHAR(20)
);
